### ISSUE TITLE
Validation of BankingProductLendingRate Schema fails with a java.lang.NumberFormatException

### ISSUE THREAD

**Issue by sushmanprasad** [ConsumerDataStandardsAustralia/java-artefacts#36]
1. Validation of BankingProductLendingRate fails with a java.lang.NumberFormatException
2. Following are the details of the exception: 

java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:494)
        at java.math.BigDecimal.<init>(BigDecimal.java:383)
        at java.math.BigDecimal.<init>(BigDecimal.java:806)
        at au.org.consumerdatastandards.conformance.util.ConformanceUtil.checkAgainstCDSDataType(ConformanceUtil.java:245)
        at au.org.consumerdatastandards.conformance.util.ConformanceUtil.checkAgainstModel(ConformanceUtil.java:58)
        at au.org.consumerdatastandards.conformance.PayloadValidator.validatePayload(PayloadValidator.java:67)
        at au.org.consumerdatastandards.conformance.PayloadValidator.validateFile(PayloadValidator.java:44)
        at au.org.consumerdatastandards.client.cli.ReferenceTest.validatePath(ReferenceTest.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
        at org.springframework.shell.Shell.evaluate(Shell.java:180)
        at org.springframework.shell.Shell.run(Shell.java:142)
        at org.springframework.shell.jline.InteractiveShellApplicationRunner.run(InteractiveShellApplicationRunner.java:84)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:794)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at au.org.consumerdatastandards.client.cli.CdsClientShell.main(CdsClientShell.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:558)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sushmanprasad** [comment]
Following are the contents of the JSON file:

{
  "lendingRateType": "FIXED",
  "rate": "string",
  "comparisonRate": "string",
  "calculationFrequency": "string",
  "applicationFrequency": "string",
  "interestPaymentDue": "IN_ARREARS",
  "tiers": [
    {
      "name": "string",
      "unitOfMeasure": "DOLLAR",
      "minimumValue": 0,
      "maximumValue": 0,
      "rateApplicationMethod": "WHOLE_BALANCE",
      "applicabilityConditions": {
        "additionalInfo": "string",
        "additionalInfoUri": "string"
      },
      "subTier": {
        "name": "string",
        "unitOfMeasure": "DOLLAR",
        "minimumValue": 0,
        "maximumValue": 0,
        "rateApplicationMethod": "WHOLE_BALANCE",
        "applicabilityConditions": {
          "additionalInfo": "string",
          "additionalInfoUri": "string"
        }
      }
    }
  ],
  "additionalValue": "string",
  "additionalInfo": "string",
  "additionalInfoUri": "string"
}

**Comment by fyang1024** [comment]
This duplicates #27
